---
title: "Teaching and leading in Open Research"
---

```{r}
#| eval: true
#| echo: false
#| warning: false
library(downlit)
library(xml2)
```

## Welcome!

Are you interested in **building on your didactic foundations** to **become an Open Research Instructor?** Or are you interested in **training future open research instructors** in delivering high-quality open research education? **Then you are in the right place!** 

On this website you will find **ready-to-use materials, hands-on activities and practical tips** providing you with **essential teaching and leadership skills** to effectively **share** your open research knowledge and skills across **different audiences** (students, researchers, research support staff etc.) and to **successfully conceptualize and deliver open research workshops**  across **different teaching settings** (courses, seminars, workshops, in-person, virtual or hybrid settings).  

### Who are these materials for?

Aspiring **open research instructors**, future **open research train-the-trainers** and **educators** in higher education (e.g., universities, colleges) and **self-learners**, with basic familiarity about open research issues and practices, aiming to:

- **Expand** their teaching and leadership skills in open research
- **Convey** foundational open research knowledge and skills to  audiences across different settings
- **Learn** more about the surrounding issues and potential challenges of teaching about open research and discussing open research issues
- **Boost their confidence** in their own teaching and leadership skills in an open research context

### What materials are there?

The materials consist of **slide decks** with **theoretical elements**, **hands-on activities** and **practical tips** for teaching and leading in open research. The materials are completely **free to use**, given that you give appropriate credit. 

Detailed **presenter notes** (intended narrative of the presentation), further **instructor notes** (additional guidance intended only for the presenter) and **accessibility tips** (where applicable) are available for each topic and are directly integrated into the slides. 

::: {.callout-tip}
## Adapting the materials
**You want to adapt the materials for your audience**? The source code for the materials as well as PowerPoint files are available for download to tailor the materials to your exact audience.
:::

### How can I use these materials?

As an **aspiring open research instructor** or **self-learner**: In the navigation menu on the left, go through each topic in a chronological order and follow along the slides and the practical exercises. You can navigate the slides in full screen using the arrow key, or by viewing the slides in *Speaker View* together with the *presenter** and **instructor notes** to understand and reflect on the content of the materials (recommended, see [here](https://quarto.org/docs/presentations/revealjs/presenting.html) for more information). If you opt for a pick-and-choose-your-topic-style, make sure to thoroughly **read the prerequisites** for each topic. For each topic, you go at your own pace and within your own timeframe.  Note: Group exercises are *not* possible in this asynchronous setting, but can be completed individually. Download as pdf or PowerPoint is possible. Make sure to give appropriate credit to the original authors if you share these files.

As a **future open research train-the-trainer**: Select your topic of choice from the navigation menu on the left. The materials are ready to be used in a classroom setting with future open research instructors as audience. Use the materials in full-screen mode directly in your browser. *Presenter** and **instructor notes* provide evidence-based guidance and practical tips on how to convey the materials to your future instructors. You can also download the corresponding PowerPoint or pdf files and **adapt the materials** to your audience. Make sure to give appropriate credit to the original authors. 

::: {.callout-important}
## Read the introductory page for each topic
When selecting a topic, you will be directed to a separate website with all the materials. Please ensure to read the *About* section, as well as details about the **intended target audience**, the **prerequisites** to complete the topic and the **learning objectives**. You can also find the contributor list, the license details and the citation statement on each website.
:::

## Getting started!

When you click the following button, it takes you directly to the topic. Enjoy!

<a href="teaching-open-research/core-didactic-principles/index.html" target="_blank" 
   style="display:inline-block;
          padding:12px 20px;
          background-color:#009933;
          color:white;
          text-decoration:none;
          border-radius:8px;
          font-weight:bold;">
  Get started!
</a>


## How can I give feedback on the materials?

Do you feel like there is **content missing** from the slides? Have you spotted another **way to improve our materials**, or would like to add or **contribute** to the materials? **We would love to hear your feedback!** There are different ways to give feedback:

- **The quick and easy way**: Contact the program coordinator, [Sarah von Grebmer](mailto:s.grebmer@lmu.de) (LMU Open Science Center).

- **The pro way** (involves GitHub): Navigate to the GitHub repository and open an issue, see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/creating-an-issue) for instructions on how to do this. Provide a descriptive title for your feedback, and describe your feedback in greater detail in the text box. Include which materials you want to provide feedback on, what the issue is and if it is low, medium or high priority. Tag Sarah von Grebmer (using her GitHub username [SvonGrebmer](https://github.com/SvonGrebmer)). 

## Frequently asked questions

1. **What previous teaching experience do I need?**

No prior teaching experience is required! The materials will introduce you to the teaching basics. It is helpful if you have given any kind of presentation before.
  
2. **Do I need to be familiar with open research to use these materials?**

Yes! We do require a basic familiarity with open research principles. This is because the aim of the current materials is to develop your pedagogical skills to convey your open research knowledge and skills to different audiences. The pedagogy guidance and practical activities we provide draws upon open research practices (e.g., *navigating challenges to preregistration*). If you feel like you need to develop your open research skills first, please browse the available self-paced tutorials in our [self-learning catalogue](https://ree-gupta.github.io/lmu-osc.github.io/training/self_training.html).

3. **I am not a member of the LMU Open Science Center, can I still use these materials to develop my skills?**

Yes! These materials are made for instructors, educators and self-learners beyond the LMU Munich. However, if you are based at LMU, consider [joining the LMU Open Science Center](https://lmu-osc.github.io/about/join-us.html) to support the goal of open, responsible, and reproducible research within your disciplines or at LMU Munich more broadly.

::: {.callout-note}
## Cannot find the answer you are looking for?
Please get in touch with the program coordinator, [Sarah von Grebmer](mailto:s.grebmer@lmu.de) (LMU Open Science Center).
:::

## Licence and citation statement

::: {.callout-note}
## How to cite these materials while they are work in progress
Von Grebmer Zu Wolfsthurn, S., Middleton S., Ihle, M., & Schönbrodt, F. (2026). *Teaching and leading in Open Research*. LMU Open Science Center. Retrieved Septebmer 22, 2026, from [https://lmu-osc.github.io/train-the-trainer-open-research/](https://lmu-osc.github.io/train-the-trainer-open-research/)
:::

Unless otherwise specified, the text, images and supplementary materials on these pages is licenced under a **CC-BY-SA-4.0 [Creative Commons Attribution 4.0 International SA License](https://creativecommons.org/licenses/by-sa/4.0/deed.en)**. It permits unrestricted re-use, distribution, and reproduction in any medium, provided the original work is properly cited. If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

Note that code embedded in these materials is licenced under a **CC0 [Creative Commons 0 Public Domain License](https://creativecommons.org/public-domain/cc0/)**. This licence enables the creators of these materials to waive their copyright and related rights worldwide, placing a work as close as legally possible into the public domain so that others may freely build upon, enhance and reuse the works for any purposes without restriction under copyright or database law.

## List of contributors

- Sarah von Grebmer zu Wolfsthurn, [ORCID 0000-0002-6413-3895](https://orcid.org/0000-0002-6413-3895), LMU Open Science Center

- Sara Middleton, [ORCID 0000-0001-5307-8029](https://orcid.org/0000-0001-5307-8029), LMU Open Science Center

- Malika Ihle, [ORCID 0000-0002-3242-5981](https://orcid.org/0000-0002-3242-5981), LMU Open Science Center

- Felix Schönbrodt, [ORCID 0000-0002-8282-3910](https://orcid.org/0000-0002-8282-3910), LMU Open Science Center and Ludwig-Maximilians-Universität München, Faculty of Psychology and Pedagogy


## Funding and partners

This project is funded by the [VolksWagen Foundation](https://www.volkswagenstiftung.de/de) and is developed in collaboration with [FORRT](https://forrt.org/).


:::: {.columns}

::: {.column width="47.5%"}

::: {.callout-tip title="Support the LMU Open Science Center!"}

**Like these materials? Be sure to give [the repository]({{< meta repo-url >}}) a star and [follow us on GitHub](https://github.com/lmu-osc)!**
:::

:::

::: {.column width="5%"}
:::

::: {.column width="47.5%"}

::: {.callout-tip title="Questions about these materials?"}
**If you have questions for the authors of these materials, please take a look at the [About](about.qmd) page.**
:::

:::

::::
